sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - tree
before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update && brew install tree fi
after_failure:
  - tree -h
env:
  global:
    - RUST_BACKTRACE=1
